language: node_js
node_js:
- node
before_install: cd Server
script:
- npm run test
- npm run publish-coverage
deploy:
  provider: heroku
  api_key:
    secure: fP2RxoiViHCoOziILCUu+le4zgdMr4ZZlWyKMFN8pRC4qW1FX7K99kLjxahEThzQSlbWI6vRubfmVKXdnHuOszyZsfkfhmexciR0D5+ta2/G7qqBZ2fWN6HroPXEZ6LUFiCMvE4y9qO5CsFSjObC6QZQjwiXwS27fIauHdk7KvIYJjvVSYrOXV9sCrcq1MIBNQ6zwUfny+CwHAUDXTseOmt8R16HMkJb2olepPYgkkNDIh7NYHRFtlp2gHSYvrEIZAKTMFxukIYN5iwNk/MOZIxjUmwkvig38Sk7ALIH5kAl76ePJI+3/Huh7Ys3VyRMUR6/HIR5VU78hdMZMam6z0hv7QW4QGOjgvQ145MVNmVgnnNqdpC1/MZ0CW6vd+qQKwPr9v2d18oCXbuXvnuMbHhP6YPxo0SExggnZYe34rXU5zSjS9G38Bzoy3xDrydbjF3LaLwHk6L5CdsFij79NRX3dqNN5BU9simtYZfhQAj2zT2OTBWuJPZDLFm5v5NqPfHx+ph4D7ESUpYJ4VxVBV2hnAwVS9YmofGoxdopPWumHuJ0nQx81GYjAU3XoAdfHC9AESJ3ytJNsYuZi0PYgozcwdxOPwBGsIzK3rhEWJbQ86VgUxT03BqrMXxoIPAAKG3fOe234j57nua7yQExHD/m7laFnfe28cCHXszmvac=
  app: dcms-test
  on:
    repo: glenngbg/dcms
    branch: deploy-work
